version: '3.8'

services:
  # 1. Aplikasi Next.js
  app:
    container_name: bromo_app
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://touruser:tourpassword123@db:3306/tourandtravel
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
      # Ganti localhost dengan IP VPS saat deploy nanti atau biarkan jika pakai reverse proxy
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - db

  # 2. Database MySQL
  db:
    image: mysql:8.0
    container_name: bromo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: tourandtravel
      MYSQL_USER: touruser
      MYSQL_PASSWORD: tourpassword123
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # 3. phpMyAdmin (Opsional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bromo_pma
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 100M

volumes:
  mysql_data:
